# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rogue
markdown: kramdown
disqus: OhMyJaipur
google_analytics: OhMyJaipur
title: Oh My Jaipur

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Oh My Jaipur

description: The Pink City of India
disqus: dbyll-ghost # add disqus short name here
author:
  name: Oh My Jaipur
  email: ohmyjaipur@gmail.com
  github: dushyantk
  twitter: ohmyjaipur
  pinterest: asd123
  linkedin: asd123
  bio: It's all abour Jaipur and for it's People
  email_md5: 8293b53dc2d2974ee7708a1c38b38cc7

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: /dbyll
# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

gems:
  - jekyll-paginate
